SELECT "tilte", "translator", "author" FROM "longlist";
SELECT "tilte", "translator", "author" FROM "longlist" LIMIT 5;
SELECT "tilte", "translator", "author" FROM "longlist" LIMIT 12;
SELECT "author" FROM "longlist" WHERE "year" =2022;
SELECT "title", "author" FROM "longlist" WHERE "author" = 'Willem Anker';
SELECT "title", "author" FROM "longlist" WHERE "author" And "format" = 'paperback';
SELECT "title", "author" FROM "longlist" WHERE "author" And "format"!= 'paperback';
SELECT "title", "author" FROM "longlist" WHERE "year" = 2018 AND "year" = 2019;
SELECT "title", "author" FROM "longlist" WHERE "year" = 2019 AND "year" = 2020;
SELECT "tilte", "translator", "author" FROM "longlist" LIMIT 22;